### ISSUE TITLE
NAudio + MonoGame issues

### ISSUE THREAD

**Issue by MarkStudiosOfficial** [Mark-Studios/PixieTag#1]
An issue which I need to call is that NAudio is currently calling BadDeviceId calling waveOutOpen as well as MonoGame currently is having some issues with the content pipeline.

**Comment by MarkStudiosOfficial** [comment]
We need a new testing lab for MonoGame as well as I believe the dependencies of MonoGame or Administration privileges at Fenner lab is preventing NAudio.

**Comment by rurouni-hou-ou** [comment]
Why can't we just use the Fenner lab? We can both be there working on it together. Plus, it's the only place I can use any XNA/MonoGame libraries. I also don't think we should be programming it yet, design it a little first so we don't run into problems later.

**Comment by MarkStudiosOfficial** [comment]
The issue with fenner is the fact that as you saw in person that the dependencies of the new content pipeline isn't working due to the fact that it is older version of XNA/MonoGame than the current release which I'm working on so we have some compatability issues

**Comment by rurouni-hou-ou** [comment]
Like I said, just use the Fenner lab version and all will be well. Otherwise I can't do anything.

**Comment by MarkStudiosOfficial** [comment]
That is a good point but that meaning we are reverting to an older version and using the old content pipeline which is pretty much drag files in... hope for the best?

**Comment by rurouni-hou-ou** [comment]
Well how can we do it so I can use the new libraries?

**Comment by MarkStudiosOfficial** [comment]
We kill monogame devs or we complain to the university to update their monogame or we do revert to the old build and then I do a port to the new build later on when the build is finished?

**Comment by rurouni-hou-ou** [comment]
We'll try and beg the university first. Perhaps we could speak with the manager of the Fenner lab (what was his name again?) to update them. If not, then we'll revert to old version.

**Comment by MarkStudiosOfficial** [comment]
Or we speak to our "Course rep" whoever it is or attend the meeting and finally if that fails then speak to the IT admin then if that fails then revert to an old build.

**Comment by MarkStudiosOfficial** [comment]
The issue is now officially closed until thurther notice regarding the talk with the IT admins/ Course rep if that fails then we will reopen the issue confirming the milestone progress.

**Comment by rurouni-hou-ou** [comment]
We are in the Fenner lab again tomorrow so we'll ask him while we're there. Then we can proceed with the course-rep chain.
